"""The tokenizer task: implement the gpt2 BPE pretokenizer in Rust.

The editable surface is one file, tokenizer-rs/src/pretok.rs, which assembles the
gpt2 pretokenization pattern from alternation branches. The byte-pair merge in
lib.rs is fixed, so correctness is a genuine function of which branches the pattern
contains. ``apply_groups`` renders that file for a SET of covered input groups (in
canonical branch order, so any subset is a correct partial tokenizer); the oracle
then grades the real rebuilt binary with no gating.

Group -> branch mapping (canonical order):
  ascii        the letter run (ASCII class), always present (foundational)
  unicode      upgrades the letter class [A-Za-z] -> \\p{L}
  numbers      adds the number-run branch
  punctuation  adds the contraction branch + the symbol-run branch (this also
               makes code and emoji lines tokenize, since they are symbol/letter
               runs once the symbol branch exists)
  whitespace   adds the trailing / standalone whitespace branches
  code, emoji  no new branch (subsumed by ascii + punctuation); kept as group names
               so the existing category planner/cockpit still line up

apply_groups({"ascii"}) reproduces the incomplete baseline; apply_groups(all)
reproduces the exact gpt2 pattern (100% on the oracle).
"""
from __future__ import annotations

from pathlib import Path

from agents.skill import TOKENIZER as TOKENIZER_SKILL
from harness.evaluator import OracleDiffEvaluator

from ..base import Task

ROOT = Path(__file__).resolve().parents[2]
WORKSPACE = ROOT / "tokenizer-rs"
PRETOK_REL = "src/pretok.rs"
HISTORY_DIR = Path(__file__).resolve().parent / "history"

# Mirrors agents.skill.CATEGORY_ORDER so the existing category planner/improver and
# the cockpit tiles line up. ascii is foundational (always present).
GROUPS = ["ascii", "punctuation", "numbers", "code", "unicode", "whitespace", "emoji"]
FOUNDATIONAL = "ascii"

GOAL = (
    "Implement the gpt2 BPE pretokenizer in Rust (tokenizer-rs/src/pretok.rs) so the "
    "tokenizer reproduces tiktoken gpt2 token ids exactly across the fixture corpus "
    "(ascii, punctuation, numbers, code, unicode, whitespace, emoji)."
)


def _branches_for(groups: set[str]) -> list[str]:
    """The canonical-ordered regex branches that genuinely satisfy ``groups``.

    Any subset is a correct partial gpt2 pattern: lines whose every piece is covered
    by an included branch tokenize exactly, others carve the wrong pieces and fail.
    """
    branches: list[str] = []
    # contractions: 's 't 're 've 'm 'll 'd  (needed for punctuation/contractions)
    if "punctuation" in groups:
        branches.append(r"'(?:[sdmt]|ll|ve|re)")
    # letter runs, always present (ascii foundational); unicode upgrades the class
    branches.append(r" ?\p{L}++" if "unicode" in groups else r" ?[A-Za-z]++")
    # number runs
    if "numbers" in groups:
        branches.append(r" ?\p{N}++")
    # symbol / punctuation runs (also covers code symbols and emoji)
    if "punctuation" in groups:
        branches.append(r" ?[^\s\p{L}\p{N}]++")
    # whitespace runs (trailing, standalone, single)
    if "whitespace" in groups:
        branches += [r"\s++$", r"\s+(?!\S)", r"\s"]
    return branches


def _render_pretok(groups: set[str]) -> str:
    """Render the full src/pretok.rs source for the covered ``groups``."""
    branch_lines = "".join(f'        r"{b}",\n' for b in _branches_for(groups))
    covered = ", ".join(g for g in GROUPS if g in groups) or "(none)"
    return (
        "// pretok.rs - GENERATED by the swarm for the active group set.\n"
        f"// covered groups: {covered}\n"
        "//\n"
        "// The byte-pair merge in lib.rs is fixed; correctness is a function of the\n"
        "// branches below. This file is rewritten as the swarm covers more groups and\n"
        "// the oracle grades the real rebuilt binary (no gating).\n"
        "\n"
        "/// The gpt2 pretokenization pattern, assembled from its alternation branches.\n"
        "pub fn gpt2_pattern() -> String {\n"
        "    let branches = [\n"
        f"{branch_lines}"
        "    ];\n"
        "    branches.join(\"|\")\n"
        "}\n"
    )


def _apply(groups: set[str]) -> None:
    """Write src/pretok.rs to genuinely satisfy ``groups`` (ascii always on)."""
    g = set(groups) | {FOUNDATIONAL}
    (WORKSPACE / PRETOK_REL).write_text(_render_pretok(g), encoding="utf-8")


def _reset() -> None:
    """Install the intentionally-incomplete baseline (ascii only)."""
    _apply({FOUNDATIONAL})


def build_task() -> Task:
    """Build the configured tokenizer Task."""
    return Task(
        name="tokenizer",
        goal=GOAL,
        workspace=WORKSPACE,
        evaluator=OracleDiffEvaluator(),
        edit_targets=[PRETOK_REL],
        build_cmd=[
            "cargo",
            "build",
            "--release",
            "--manifest-path",
            str(WORKSPACE / "Cargo.toml"),
        ],
        build_cwd=ROOT,
        groups=GROUPS,
        skill=TOKENIZER_SKILL,
        reset_fn=_reset,
        apply_groups_fn=_apply,
        history_dir=HISTORY_DIR,
    )
