// pretok.rs - GENERATED by the swarm for the active group set.
// covered groups: ascii, punctuation, numbers, unicode, whitespace, emoji
//
// The byte-pair merge in lib.rs is fixed; correctness is a function of the
// branches below. This file is rewritten as the swarm covers more groups and
// the oracle grades the real rebuilt binary (no gating).

/// The gpt2 pretokenization pattern, assembled from its alternation branches.
pub fn gpt2_pattern() -> String {
    let branches = [
        r"'(?:[sdmt]|ll|ve|re)",
        r" ?\p{L}++",
        r" ?\p{N}++",
        r" ?[^\s\p{L}\p{N}]++",
        r"\s++$",
        r"\s+(?!\S)",
        r"\s",
    ];
    branches.join("|")
}
